language: python

python:
  - "2.7"

install:
  - "pip install ."
  - "pip install nltk"
  - "pip install numpy"
  - "pip install goose-extractor"

script:
  - export TARGET="-m unittest discover tests test_*.py"
  - python $TARGET
